// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CSharpTesting.Models;
//
//    var productionDto = ProductionDto.FromJson(jsonString);


using Newtonsoft.Json;
using System;
using static SharedLibrary.util.Util;
namespace SharedLibrary.Models;

public partial class ProductionDto
{
    public static ProductionDto FromJson(string json)
    {
            // Replace NaN with null
            json = json.Replace("NaN", "null");

            try
            {
                return JsonConvert.DeserializeObject<ProductionDto>(json, Converter.Settings);
            }
            catch (JsonReaderException ex)
            {
                LogError($"JSON Deserialization Error: {ex.Message}. JSON: {json}");
            }
        return null;
    }

    public static string ToJson(ProductionDto production)
    {
        try
        {
                var prod = production;
                prod.TimeStamp = production.Inverters.First().Production.First().TimeStamp;
                return JsonConvert.SerializeObject(production, Converter.Settings);
        }
        catch (Exception ex)
        {
            if (production != null)
            {
                LogError($"DTO to Json Error: {ex.Message}. exc: {ex}");
            }
            else
            {
                LogError($" Failed to serialize DTO to Json Error: {ex.Message}. exc: {ex}");
            }

            return null;
        }
    }
}


