// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CSharpTesting.Models;
//
//    var productionDto = ProductionDto.FromJson(jsonString);


using Newtonsoft.Json;
using System;
using static SharedLibrary.util.Util;
namespace SharedLibrary.Models;

public partial class ProductionDto
{
    public static ProductionDto FromJson(string json)
    {
        if (SharedLibrary.Azure.AzureBlobCtrl.IsValidJson(json))
        {
            // Replace NaN with null
            json = json.Replace("NaN", "null");

            try
            {
                return JsonConvert.DeserializeObject<ProductionDto>(json, Converter.Settings);
            }
            catch (JsonReaderException ex)
            {
                LogError($"JSON Deserialization Error: {ex.Message}. JSON: {json}");
                throw; // or handle accordingly
            }
        }
        return null;
    }

    public static string ToJson(ProductionDto production)
    {
        if (production == null)
        {
            return null;
        }
        return JsonConvert.SerializeObject(production, Converter.Settings);
    }
}


