// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CSharpTesting.Models;
//
//    var productionDto = ProductionDto.FromJson(jsonString);

namespace SharedLibrary.Models
{
    using Newtonsoft.Json;
    using System;
    public partial class DataPoint
    {
        [JsonProperty("timeStamp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? TimeStamp { get; set; }

        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public double Value { get; set; }

        [JsonProperty("quality", NullValueHandling = NullValueHandling.Ignore)]
        public long? Quality { get; set; }
    }
}

