// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CSharpTesting.Models;
//
//    var productionDto = ProductionDto.FromJson(jsonString);

namespace SharedLibrary.Models
{
    using Newtonsoft.Json;
    using System;
    public partial class ProductionDto
    {
        public static ProductionDto FromJson(string json)
        {
            if (json == null)
            {
                return null;
            }
        return JsonConvert.DeserializeObject<ProductionDto>(json, Converter.Settings);
        } 
        public static string ToJson(ProductionDto production) 
        {
            if (production == null)
            {
                return null;
            }
            return JsonConvert.SerializeObject(production, Converter.Settings);
        }
    }
}

