// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CSharpTesting.Models;
//
//    var productionDto = ProductionDto.FromJson(jsonString);

using System.Runtime.Serialization.Formatters.Binary;
using System.Runtime.Serialization;

namespace SharedLibrary.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    [Serializable]
    public partial class ProductionDto
    {
        [JsonProperty("timeType", NullValueHandling = NullValueHandling.Ignore)]
        public long? TimeType { get; set; }

        [JsonProperty("timeStamp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? TimeStamp { get; set; }

        [JsonProperty("inverters", NullValueHandling = NullValueHandling.Ignore)]
        public List<Inverter> Inverters { get; set; }
    }
}
