// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CSharpTesting.Models;
//
//    var productionDto = ProductionDto.FromJson(jsonString);

namespace CSharpTesting.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    public partial class Inverter
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("production", NullValueHandling = NullValueHandling.Ignore)]
        public List<DataPoint> Production { get; set; }
    }
}

