// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CSharpTesting.Models;
//
//    var productionMonth = ProductionMonth.FromJson(jsonString);

namespace CSharpTesting.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ProductionMonth
    {
        [JsonProperty("timeType", NullValueHandling = NullValueHandling.Ignore)]
        public long? TimeType { get; set; }

        [JsonProperty("timeStamp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? TimeStamp { get; set; }

        [JsonProperty("inverters", NullValueHandling = NullValueHandling.Ignore)]
        public List<Inverter> Inverters { get; set; }
    }

    public partial class Inverter
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("production", NullValueHandling = NullValueHandling.Ignore)]
        public List<Production> Production { get; set; }
    }

    public partial class Production
    {
        [JsonProperty("timeStamp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? TimeStamp { get; set; }

        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public long? Value { get; set; }

        [JsonProperty("quality", NullValueHandling = NullValueHandling.Ignore)]
        public long? Quality { get; set; }
    }
}
